import { Drink } from './Drink';
import { attribute, table, autoGeneratedHashKey } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty, ValidateNested } from 'class-validator';

@table('categories')
export class Category {

    @autoGeneratedHashKey()
    public uid: string;

    @IsNotEmpty()
    @attribute()
    public name: string;

    @attribute()
    public photoUrlLarge?: string;

    @attribute()
    public photoUrlMedium?: string;

    @attribute()
    public photoUrlSmall?: string;

    @IsNotEmpty()
    @ValidateNested()
    @attribute()
    public drinks: Drink[];

    constructor() {
        this.drinks = [];
    }

}